hanoiexe: hanoi.o
	g++ -Wall -std=c++11 -g -o hanoiexe hanoi.o
	
hanoi: hanoi.cpp
	g++ -Wall -std=c++11 -g -c hanoi.cpp
	
prog13exe: prog_13.o prog_13_unit_test.o
	g++ -Wall -std=c++11 -g -o prog13exe prog_13.o prog_13_unit_test.o
	
prog13: prog_13.cpp
	g++ -Wall -std=c++11 -g -c prog_13.cpp
	
prog13unittest: prog_13_unit_test.cpp
	g++ -Wall -std=c++11 -g -c prog_13_unit_test.cpp
	
prog16exe: prog_16.o prog_16_unit_test.o
	g++ -Wall -std=c++11 -g -o prog16exe prog_16.o prog_16_unit_test.o
	
prog16: prog_16.cpp
	g++ -Wall -std=c++11 -g -c prog_16.cpp
	
prog16unittest: prog_16_unit_test.cpp
	g++ -Wall -std=c++11 -g -c prog_16_unit_test.cpp
	
clean:
	rm *.o *test