Pairexe: Pair.o
	g++ -Wall -std=c++11 -g -o Pairexe Pair.o
	
Pair: Pair.cpp Pair.h 
	g++ -Wall -std=c++11 -g -c Pair.cpp Pair.h
	
Petsexe: Pets.o
	g++ -Wall -std=c++11 -g -o Petsexe Pets.o
	
Pets: Pets.cpp Pets.h
	g++ -Wall -std=c++11 -g -c Pets.cpp Pets.h
	
Predatorexe: Predator.o
	g++ -Wall -std=c++11 -g -o Predatorexe Predator.o
	
Predator: Predator.cpp Predator.h
	g++ -Wall -std=c++11 -g -c Predator.cpp Predator.h
	
clean:
	rm *.o *test