moviexe: movie_map.o
	g++ -Wall -std=c++11 -g -o moviexe map.o
	
movie: movie_map.cpp
	g++ -Wall -std=c++11 -g -c movie_map.cpp
	
steamexe:
	g++ -Wall -std=c++11 -g -o steamexe

steam: 
	g++ -wall -std=c++11 -g -c 
	
clean:
	rm *.o *test